language: node_js
node_js:
  - 10
  - 11
  - 12
  - 13
  - 14

cache:
  directories:
  - node_modules

before_script:
  - npm run bootstrap

script:
  - npm run test

jobs:
  include:
    - stage: Deploy to npm
      node_js: 14
      script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run build
          - npm run publish
        on:
          branch: master
