name: Update and Test Angular

on:
  push:
    branches:
      - main

jobs:
  update-angular:
    name: Update Angular
    runs-on: ubuntu-latest

    strategy:
      matrix:
        angular-version:
          - '14.x.x'
          - '15.x.x'
          - '16.x.x'
        node-version:
          - '14.20.x'
          - '16.14.x'
          - '18.10.x'

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        run: |
          nvm install ${{ matrix.node-version }}
          nvm use ${{ matrix.node-version }}

      - name: Angular 14
        if: matrix.angular-version == '14.x.x'
        run: |
          npm install -g @angular/cli@14 @angular/core@14
          npm install
          npm run test
          npm run build

      - name: Angular 15
        if: matrix.angular-version == '15.x.x'
        run: |
          npm install -g @angular/cli@15 @angular/core@15
          npm install
          npm run test
          npm run build

      - name: Angular 16
        if: matrix.angular-version == '16.x.x'
        run: |
          npm install -g @angular/cli@16 @angular/core@16
          npm install
          npm run test
          npm run build
